GET http://{{host}}
content-type: application/json

###

GET http://{{host}}/api/info

###

GET http://{{host}}/api/devices

###

GET http://{{host}}/api/devices/xiaomi

###
GET http://{{host}}/api/devices/caniot

###

GET http://{{host}}/metrics

###

GET http://{{host}}/404

###

GET http://{{host}}/api/devices/caniot/40/endpoint/3/telemetry

###

POST http://{{host}}/api/devices/garage

{
    "left_door": "set",
    "right_door": "none"
}

###

GET http://{{host}}/api/devices/caniot/32/endpoints/3/telemetry

###

POST http://{{host}}/api/files

TEST

###

GET http://{{host}}/api/files/lua

###

GET http://{{host}}/api/test/payload

MYPAYLOAD

###

GET http://{{host}}/api/test/route_args/23/1/24?test=sdf&fdsf=826h&name=Lucas&&qsfd=86

###


GET http://{{host}}/metrics_controller

###

GET http://{{host}}/api/credentials/flash