GET http://{{host}}
content-type: application/json

###

GET http://{{host}}/info

###

GET http://{{host}}/devices

###

GET http://{{host}}/devices/xiaomi

###
GET http://{{host}}/devices/caniot

###

GET http://{{host}}/metrics

###

GET http://{{host}}/404

###

GET http://{{host}}/devices/caniot/24/ll/3/query_telemetry

###

POST http://{{host}}/devices/garage

{
    "left_door": "set",
    "right_door": "none"
}

###

GET http://{{host}}/devices/caniot/32/endpoints/3/telemetry

###

POST http://{{host}}/files

TEST